services:
  sqlserverERP:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverERP
    ports:
      - "1434:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "123John@"
    volumes:
      - sqlserverERP_data:/var/opt/mssql

  usuarios-service:
    build:
      context: .
      dockerfile: UsuariosAPI/Dockerfile
    depends_on:
      - sqlserverERP
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=AbcdefghijklmnopqrstuvwxyZ123456!
      - ConnectionStrings__DefaultConnection=server=sqlserverERP;Database=UsuariosDb;User=sa;Password=123John@;TrustServerCertificate=True;
    ports:
      - "6007:8080"
volumes:
  sqlserverERP_data:
